#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=50
STOP=50

USE_PROCD=1

PROG="/usr/sbin/vsftpd"

start_service() {
	echo starting vsftpd
	mkdir -m 0755 -p /var/run/vsftpd
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_set_param file /etc/vsftpd.conf
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

